{{- if and .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ include "k8s.namespace" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "k8s.dockerconfigjson" . }}
{{- else }}
{{- fail "imageCredentials.registry, imageCredentials.username, and imageCredentials.password are required" }}
{{- end }}