apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-web-service.fullname" . }}-service
  namespace: {{ include "python-web-service.namespace" . }}
  labels:
    {{- include "python-web-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "python-web-service.selectorLabels" . | nindent 4 }}
