apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-collector-secret
  namespace: opentelemetry-operator # Use your namespace
data:
  # The value must be base64 encoded
  LS_TOKEN: ${LS_TOKEN_BASE64}
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
data:
  DT_ENDPOINT: ${DT_ENDPOINT}