apiVersion: v2
name: o11y
description: A Helm chart for OpenTelemetry Collector deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - opentelemetry
  - otel
  - rbac
  - collector
maintainers:
  - name: Andriy Kandzyuba
    email: andriy.kandzyuba@dynatrace.com
