apiVersion: v2
name: k8s
description: A Helm chart for deploying K8s infra for applications
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - k8s
  - docker
  - registry
  - secret
  - imagePullSecrets
maintainers:
  - name: Andriy Kandzyuba
    email: andriy.kandzyuba@dynatrace.com
