apiVersion: v2
name: python-web-service
description: A Helm chart for Python Web Service with OpenTelemetry and Prometheus metrics
type: application
version: 0.1.0
appVersion: "0.0.3"
keywords:
  - python
  - web-service
  - prometheus
  - opentelemetry
maintainers:
  - name: Andriy Kandzyuba
    email: andriy.kandzyuba@dynatrace.com
