name: Provision System Resources to K8s

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
        default: dev

# Required if using OIDC for authentication in 2026
permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Print Context Info'
        run: |
          echo "Environment Name: ${{ env.DEPLOY_ENV }}"
          echo "Apps Namespace Prefix: ${{ vars.K8S_NS_APPS_PREFIX }}"

      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Verify kubectl access'
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: create secret docker-registry ${{ vars.REGISTRY_SECRET_NAME }} \ 
            --docker-server=${{ vars.REGISTRY_LOGIN_SERVER }} \
            --docker-username=${{ secrets.REGISTRY_USERNAME }} \
            --docker-password=${{ secrets.REGISTRY_PASSWORD }} \
            --docker-email=${{ vars.REGISTRY_EMAIL }} \
            -n ${{ vars.K8S_NS_APPS_PREFIX }}-${{ env.DEPLOY_ENV }} \
            --dry-run='none'